# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://blog.jez.io
title: Bits, Bytes, and Words
subtitle: Jake Zimmerman
author: Jake Zimmerman
description: A tech blog by Jake Zimmerman. Updates occasionally with tips, tricks, hacks, and personal projects.
author_bio: "Studying computer science at Carnegie Mellon. Stripe, Dropbox, Bloomberg."
about: https://jez.io
future: false
timezone: America/New_York

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email: jake@zimmerman.io
# RSS feeds can list your email address if you like
email: jake@zimmerman.io

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart

paginate: 20          # Posts per page on the blog index
paginate_path: "posts/:num/"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: 'Continue reading &nbsp; <i class="fa fa-angle-double-right"></i>'  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: +JacobZimmerman0

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Jake
    url: https://jez.io
    external: true
  - title: GitHub
    url: https://github.com/jez
    external: true
